### ISSUE TITLE
Graphical Pie Chart

### ISSUE THREAD

**Issue by dongola7** [dongola7/Time-Track-CLI#10]
Have an option to pop up a graphical pie chart using data from the summary.  Possibly allow for drill down from charge codes to individual tasks.

**Comment by dongola7** [comment]
See the Tcl Wiki for some example pie chart code http://wiki.tcl.tk/17968.

**Comment by neilernst** [comment]
Even cooler would be the option to upload to Google Spreadsheet Charts, or something like Daytum.

**Comment by dongola7** [comment]
What were you thinking in terms of Google Spreadsheets?  Posting weekly timesheets with breakdowns per day?  Something else?

Doesn't look like Daytum has a public API yet.

**Comment by neilernst** [comment]
For Daytum I was thinking using the Twitter aspect via something like twtr. When a task is stopped post a message to twitter or direct message to Daytum via Twitter.

**Comment by dongola7** [comment]
Note for later: This link describes the daytum/twitter integration: http://daytum.wordpress.com/2008/11/06/mobile-submissions/

**Comment by dongola7** [comment]
This request is being implemented in the form of 'command hooks'.  I'm going to commit a new feature that allows creation of a post-stop script that will be executed each time you stop a task.  An example script includes documentation on how you can use this to post to twitter (or Daytum via twitter).

**Comment by dongola7** [comment]
Implementing command hooks.  Currently only post-stop is implemented.

Command hooks allow a user to inject functionality when at various points
while time_track.tcl is executing.  The post-stop hook, for example, allows
a user to send notifications that a task has stopped.

Closed by 52558acdd288d4d14a35aff35147f08cfd142544.
